/**:
  ros__parameters:
    camera:
      i_pipeline_type: "RGBD"
      # i_rs_compat: true
      i_nn_type: none
      i_laser_dot_brightness: 1000
      i_publish_tf_from_calibration: false 
    rgb:
      i_resolution: "720P"
      i_width: 1280   # Explicitly set width
      i_height: 720  # Explicitly set height
      i_fps: 10.0
      #! runtime parameters
      r_set_man_exposure: true
      r_exposure: 15000  # us
      r_iso: 200
    left:
      i_resolution: "400P"
      i_publish_topic: false

    right:
      i_resolution: "400P"
      i_publish_topic: false

    stereo:
      i_align_depth: true
      i_subpixel: true
      i_stereo_conf_threshold: 110
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 1
      i_brightness_filter_max_brightness: 225
      i_enable_decimation_filter: true
      i_publish_left_rect: false
      i_publish_right_rect: false