/**:
  ros__parameters:

    controller_name: "/joint_trajectory_controller"
    wait_sec_between_publish: 1

    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint

    check_starting_point: false
